### ISSUE TITLE
IllegalArgumentException when adding renarde as a dependency

### ISSUE THREAD

**Issue by dwamara** [FroMage/quarkus-renarde-todo#1]
I've just create a simple Quarkus project which started fine. As soon as I added the renarde dependency (version 1.0.0) in the pom.xml, I've started getting following error which doesn't seem to disappear no matter what I do:

`2022-05-09 00:19:58,184 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.qute.deployment.QuteProcessor#collectTemplates threw an exception: java.lang.IllegalArgumentException
	at jdk.zipfs/jdk.nio.zipfs.ZipPath.relativize(ZipPath.java:230)
	at io.quarkus.qute.deployment.QuteProcessor.scan(QuteProcessor.java:2301)
	at io.quarkus.qute.deployment.QuteProcessor.scan(QuteProcessor.java:2313)
.....
`

Any idea how to fix this?

D.

**Comment by FroMage** [comment]
Which version of Quarkus are you using?

**Comment by FroMage** [comment]
Also, I think this is a question for Renarde: https://github.com/quarkiverse/quarkus-renarde/issues not for the todo example application, could you move it there please?

**Comment by dwamara** [comment]
Sorry, I was too hooked on the todo example, I'm moving the issue there and will be answering the question there too. It was still strange that I had the first issue :-)
